typeof document.attachEvent!="undefined"?(window.attachEvent("onload",init),document.attachEvent("onmousemove",moveMouse),document.attachEvent("onclick",checkMove)):(window.addEventListener("load",init,!1),document.addEventListener("mousemove",moveMouse,!1),document.addEventListener("click",checkMove,!1));
var oDv=document.createElement("div"),dvHdr=document.createElement("div"),dvBdy=document.createElement("div"),windowlock,boxMove,fixposx,fixposy,lockX,lockY,fixx,fixy,ox,oy,boxLeft,boxRight,boxTop,boxBottom,evt,mouseX,mouseY,boxOpen,totalScrollTop,totalScrollLeft;boxOpen=!1;oy=ox=10;lockY=lockX=0;function init(){oDv.appendChild(dvHdr);oDv.appendChild(dvBdy);oDv.style.position="absolute";oDv.style.visibility="hidden";oDv.style.zIndex="999";document.body.appendChild(oDv)}function defHdrStyle(){}
function defBdyStyle(){dvBdy.style.width="200px";dvBdy.style.padding="5px";dvBdy.style.color="#ffffff";dvBdy.style.background="#000000";dvBdy.style.filter="alpha(opacity=65)";dvBdy.style.opacity="0.65"}function checkElemBO(a){if(!a||typeof a!="string")return!1;return a.indexOf("header")>-1&&a.indexOf("body")>-1&&a.indexOf("[")>-1&&a.indexOf("[")>-1?!0:!1}
function scanBO(a){checkElemBO(a.title)?(a.boHDR=getParam("header",a.title),a.boBDY=getParam("body",a.title),a.boCSSBDY=getParam("cssbody",a.title),a.boCSSHDR=getParam("cssheader",a.title),a.IEbugfix=getParam("hideselects",a.title)=="on"?!0:!1,a.fixX=parseInt(getParam("fixedrelx",a.title)),a.fixY=parseInt(getParam("fixedrely",a.title)),a.absX=parseInt(getParam("fixedabsx",a.title)),a.absY=parseInt(getParam("fixedabsy",a.title)),a.offY=getParam("offsety",a.title)!=""?parseInt(getParam("offsety",a.title)):
10,a.offX=getParam("offsetx",a.title)!=""?parseInt(getParam("offsetx",a.title)):10,a.fade=getParam("fade",a.title)=="on"?!0:!1,a.fadespeed=getParam("fadespeed",a.title)!=""?getParam("fadespeed",a.title):0.04,a.delay=getParam("delay",a.title)!=""?parseInt(getParam("delay",a.title)):0,getParam("requireclick",a.title)=="on"?(a.requireclick=!0,document.all?a.attachEvent("onclick",showHideBox):a.addEventListener("click",showHideBox,!1),document.all?a.attachEvent("onmouseover",hideBox):a.addEventListener("mouseover",
hideBox,!1)):(getParam("doubleclickstop",a.title)!="off"&&(document.all?a.attachEvent("ondblclick",pauseBox):a.addEventListener("dblclick",pauseBox,!1)),getParam("singleclickstop",a.title)=="on"&&(document.all?a.attachEvent("onclick",pauseBox):a.addEventListener("click",pauseBox,!1))),a.windowLock=getParam("windowlock",a.title).toLowerCase()=="off"?!1:!0,a.title="",a.hasbox=1):a.hasbox=2}
function getParam(a,b){var c=RegExp("([^a-zA-Z]"+a+"|^"+a+")\\s*=\\s*\\[\\s*(((\\[\\[)|(\\]\\])|([^\\]\\[]))*)\\s*\\]").exec(b);return c?c[2].replace("[[","[").replace("]]","]"):""}function Left(a){var b=0;if(a.calcLeft)return a.calcLeft;for(var c=a;a;)a.currentStyle&&!isNaN(parseInt(a.currentStyle.borderLeftWidth))&&b!=0&&(b+=parseInt(a.currentStyle.borderLeftWidth)),b+=a.offsetLeft,a=a.offsetParent;return c.calcLeft=b}
function Top(a){var b=0;if(a.calcTop)return a.calcTop;for(var c=a;a;)a.currentStyle&&!isNaN(parseInt(a.currentStyle.borderTopWidth))&&b!=0&&(b+=parseInt(a.currentStyle.borderTopWidth)),b+=a.offsetTop,a=a.offsetParent;return c.calcTop=b}var ah,ab;
function applyStyles(){ab&&oDv.removeChild(dvBdy);ah&&oDv.removeChild(dvHdr);dvHdr=document.createElement("div");dvBdy=document.createElement("div");CBE.boCSSBDY?dvBdy.className=CBE.boCSSBDY:defBdyStyle();CBE.boCSSHDR?dvHdr.className=CBE.boCSSHDR:defHdrStyle();dvHdr.innerHTML=CBE.boHDR;dvHdr.style.zindex="2";dvBdy.innerHTML=CBE.boBDY;dvBdy.style.zindex="2";ab=ah=!1;CBE.boHDR!=""&&(oDv.appendChild(dvHdr),ah=!0);CBE.boBDY!=""&&(oDv.appendChild(dvBdy),ab=!0)}
var CSE,iterElem,LSE,CBE,LBE,width,height,ini=!1;function SHW(){if(document.body&&document.body.clientWidth!=0)width=document.body.clientWidth,height=document.body.clientHeight;if(document.documentElement&&document.documentElement.clientWidth!=0&&document.body.clientWidth+20>=document.documentElement.clientWidth)width=document.documentElement.clientWidth,height=document.documentElement.clientHeight;return[width,height]}var ID=null;
function moveMouse(a){a?evt=a:evt=event;CSE=evt.target?evt.target:evt.srcElement;if(!CSE.hasbox)for(iElem=CSE;iElem.parentNode&&!iElem.hasbox;)scanBO(iElem),iElem=iElem.parentNode;if(CSE!=LSE&&!isChild(CSE,dvHdr)&&!isChild(CSE,dvBdy)){if(!CSE.boxItem){for(iterElem=CSE;iterElem.hasbox==2&&iterElem.parentNode;)iterElem=iterElem.parentNode;CSE.boxItem=iterElem}if((iterElem=CSE.boxItem)&&CSE.boxItem.hasbox==1)LBE=CBE,CBE=iterElem,CBE!=LBE&&(applyStyles(),CBE.requireclick||(CBE.fade?(ID!=null&&clearTimeout(ID),
ID=setTimeout("fadeIn("+CBE.fadespeed+")",CBE.delay)):(ID!=null&&clearTimeout(ID),COL=1,ID=setTimeout("oDv.style.visibility='visible';ID=null;",CBE.delay))),CBE.IEbugfix&&hideSelects(),fixposx=!isNaN(CBE.fixX)?Left(CBE)+CBE.fixX:CBE.absX,fixposy=!isNaN(CBE.fixY)?Top(CBE)+CBE.fixY:CBE.absY,lockY=lockX=0,boxMove=!0,ox=CBE.offX?CBE.offX:10,oy=CBE.offY?CBE.offY:10);else if(!isChild(CSE,dvHdr)&&!isChild(CSE,dvBdy)&&boxMove&&(!isChild(CBE,CSE)||CSE.tagName!="TABLE"))CBE=null,ID!=null&&clearTimeout(ID),
fadeOut(),showSelects();LSE=CSE}else if((isChild(CSE,dvHdr)||isChild(CSE,dvBdy))&&boxMove){totalScrollTop=totalScrollLeft=0;for(iterElem=CSE;iterElem;)isNaN(parseInt(iterElem.scrollTop))||(totalScrollTop+=parseInt(iterElem.scrollTop)),isNaN(parseInt(iterElem.scrollLeft))||(totalScrollLeft+=parseInt(iterElem.scrollLeft)),iterElem=iterElem.parentNode;CBE!=null&&(boxLeft=Left(CBE)-totalScrollLeft,boxRight=parseInt(Left(CBE)+CBE.offsetWidth)-totalScrollLeft,boxTop=Top(CBE)-totalScrollTop,boxBottom=parseInt(Top(CBE)+
CBE.offsetHeight)-totalScrollTop,doCheck())}if(boxMove&&CBE)bodyScrollTop=document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop,bodyScrollLeft=document.documentElement&&document.documentElement.scrollLeft?document.documentElement.scrollLeft:document.body.scrollLeft,mouseX=evt.pageX?evt.pageX-bodyScrollLeft:evt.clientX-document.body.clientLeft,mouseY=evt.pageY?evt.pageY-bodyScrollTop:evt.clientY-document.body.clientTop,CBE&&CBE.windowLock&&
(mouseY<-oy?lockY=-mouseY-oy:lockY=0,mouseX<-ox?lockX=-mouseX-ox:lockX=0,mouseY>SHW()[1]-oDv.offsetHeight-oy&&(lockY=-mouseY+SHW()[1]-oDv.offsetHeight-oy),mouseX>SHW()[0]-dvBdy.offsetWidth-ox&&(lockX=-mouseX-ox+SHW()[0]-dvBdy.offsetWidth)),oDv.style.left=fixposx||fixposx==0?fixposx+"px":bodyScrollLeft+mouseX+ox+lockX+"px",oDv.style.top=fixposy||fixposy==0?fixposy+"px":bodyScrollTop+mouseY+oy+lockY+"px"}
function doCheck(){if(mouseX<boxLeft||mouseX>boxRight||mouseY<boxTop||mouseY>boxBottom)CBE.IEbugfix&&showSelects(),CBE=null}function pauseBox(a){a?evt=a:evt=event;boxMove=!1;evt.cancelBubble=!0}function showHideBox(){oDv.style.visibility=oDv.style.visibility!="visible"?"visible":"hidden"}function hideBox(){oDv.style.visibility="hidden"}var COL=0,stopfade=!1;function fadeIn(a){ID=null;COL=0;oDv.style.visibility="visible";fadeIn2(a)}
function fadeIn2(a){COL+=a;COL=COL>1?1:COL;oDv.style.filter="alpha(opacity="+parseInt(100*COL)+")";oDv.style.opacity=COL;COL<1&&setTimeout("fadeIn2("+a+")",20)}function fadeOut(){oDv.style.visibility="hidden"}function isChild(a,b){for(;a;){if(a==b)return!0;a=a.parentNode}return!1}var cSrc;function checkMove(a){a?evt=a:evt=event;cSrc=evt.target?evt.target:evt.srcElement;!boxMove&&!isChild(cSrc,oDv)&&(fadeOut(),CBE&&CBE.IEbugfix&&showSelects(),boxMove=!0,CBE=null)}
function showSelects(){var a=document.getElementsByTagName("select");for(i=0;i<a.length;i++)a[i].style.visibility="visible"}function hideSelects(){var a=document.getElementsByTagName("select");for(i=0;i<a.length;i++)a[i].style.visibility="hidden"};