if(typeof com=="undefined")var com={};if(typeof com.deconcept=="undefined")com.deconcept={};if(typeof com.deconcept.util=="undefined")com.deconcept.util={};if(typeof com.deconcept.FlashObjectUtil=="undefined")com.deconcept.FlashObjectUtil={};
com.deconcept.FlashObject=function(a,c,b,d,e,f,g,h,i,j,k){if(document.createElement&&document.getElementById)this.DETECT_KEY=k?k:"detectflash",this.skipDetect=com.deconcept.util.getRequestParameter(this.DETECT_KEY),this.params={},this.variables={},this.attributes=[],this.useExpressInstall=g,a&&this.setAttribute("swf",a),c&&this.setAttribute("id",c),b&&this.setAttribute("width",b),d&&this.setAttribute("height",d),e&&this.setAttribute("version",new com.deconcept.PlayerVersion(e.toString().split("."))),
this.installedVer=com.deconcept.FlashObjectUtil.getPlayerVersion(this.getAttribute("version"),g),f&&this.addParam("bgcolor",f),this.addParam("quality",h?h:"high"),this.setAttribute("xiRedirectUrl",i?i:window.location),this.setAttribute("redirectUrl",""),j&&this.setAttribute("redirectUrl",j)};
com.deconcept.FlashObject.prototype={setAttribute:function(a,c){this.attributes[a]=c},getAttribute:function(a){return this.attributes[a]},addParam:function(a,c){this.params[a]=c},getParams:function(){return this.params},addVariable:function(a,c){this.variables[a]=c},getVariable:function(a){return this.variables[a]},getVariables:function(){return this.variables},createParamTag:function(a,c){var b=document.createElement("param");b.setAttribute("name",a);b.setAttribute("value",c);return b},getVariablePairs:function(){var a=
[],c,b=this.getVariables();for(c in b)a.push(c+"="+b[c]);return a},getFlashHTML:function(){var a="";if(navigator.plugins&&navigator.mimeTypes&&navigator.mimeTypes.length){this.getAttribute("doExpressInstall")&&this.addVariable("MMplayerType","PlugIn");a='<embed type="application/x-shockwave-flash" src="'+this.getAttribute("swf")+'" width="'+this.getAttribute("width")+'" height="'+this.getAttribute("height")+'"';a+=' id="'+this.getAttribute("id")+'" name="'+this.getAttribute("id")+'" ';var c=this.getParams(),
b;for(b in c)a+=[b]+'="'+c[b]+'" ';b=this.getVariablePairs().join("&");b.length>0&&(a+='flashvars="'+b+'"');a+="/>"}else{this.getAttribute("doExpressInstall")&&this.addVariable("MMplayerType","ActiveX");a='<object id="'+this.getAttribute("id")+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="'+this.getAttribute("width")+'" height="'+this.getAttribute("height")+'">';a+='<param name="movie" value="'+this.getAttribute("swf")+'" />';c=this.getParams();for(b in c)a+='<param name="'+b+'" value="'+
c[b]+'" />';b=this.getVariablePairs().join("&");b.length>0&&(a+='<param name="flashvars" value="'+b+'" />');a+="</object>"}return a},write:function(a){if(this.useExpressInstall){if(this.installedVer.versionIsValid(new com.deconcept.PlayerVersion([6,0,65]))&&!this.installedVer.versionIsValid(this.getAttribute("version")))this.setAttribute("doExpressInstall",!0),this.addVariable("MMredirectURL",escape(this.getAttribute("xiRedirectUrl"))),document.title=document.title.slice(0,47)+" - Flash Player Installation",
this.addVariable("MMdoctitle",document.title)}else this.setAttribute("doExpressInstall",!1);this.skipDetect||this.getAttribute("doExpressInstall")||this.installedVer.versionIsValid(this.getAttribute("version"))?(typeof a=="string"?document.getElementById(a):a).innerHTML=this.getFlashHTML():this.getAttribute("redirectUrl")!=""&&document.location.replace(this.getAttribute("redirectUrl"))}};
com.deconcept.FlashObjectUtil.getPlayerVersion=function(a,c){var b=new com.deconcept.PlayerVersion(0,0,0);if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(b=new com.deconcept.PlayerVersion(d.description.replace(/([a-z]|[A-Z]|\s)+/,"").replace(/(\s+r|\s+b[0-9]+)/,".").split(".")))}else{try{for(var d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),e=3;d!=null;e++)d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+e),b=new com.deconcept.PlayerVersion([e,
0,0])}catch(f){}if(a&&b.major>a.major)return b;if(!a||(a.minor!=0||a.rev!=0)&&b.major==a.major||b.major!=6||c)try{b=new com.deconcept.PlayerVersion(d.GetVariable("$version").split(" ")[1].split(","))}catch(g){}}return b};com.deconcept.PlayerVersion=function(a){this.major=parseInt(a[0])||0;this.minor=parseInt(a[1])||0;this.rev=parseInt(a[2])||0};
com.deconcept.PlayerVersion.prototype.versionIsValid=function(a){if(this.major<a.major)return!1;if(this.major>a.major)return!0;if(this.minor<a.minor)return!1;if(this.minor>a.minor)return!0;if(this.rev<a.rev)return!1;return!0};com.deconcept.util={getRequestParameter:function(a){var c=document.location.search||document.location.hash;if(c){var a=c.indexOf(a+"="),b=c.indexOf("&",a)>-1?c.indexOf("&",a):c.length;if(c.length>1&&a>-1)return c.substring(c.indexOf("=",a)+1,b)}return""},removeChildren:function(a){for(;a.hasChildNodes();)a.removeChild(a.firstChild)}};
if(Array.prototype.push==null)Array.prototype.push=function(a){this[this.length]=a;return this.length};var getQueryParamValue=com.deconcept.util.getRequestParameter,FlashObject=com.deconcept.FlashObject;